### ISSUE TITLE
Unlimited positional and unlimitied option

### ISSUE THREAD

**Issue by harrywong** [CLIUtils/CLI11#102]
Hi, have a question. I have a situation where there's one unlimited positional and one unlimited option. Like this:

```cpp
std::vector<std::string> t1, t2;
app->add_option("test1", t1);
app->add_option("--test2", t2);
```

If you give these arguments:  `./test a b c --test2 d e f`, then `a b c` and `e f` will go to `t1`, and only `d` will go to `t2`.

I've seen in the source code:

https://github.com/CLIUtils/CLI11/blob/b7c031cc3e758b4ea7728c818e0edcbfe7f96c4c/include/CLI/App.hpp#L1465

Could you please explain why you design like this? I think in this situation, `d e f` should go to `t2`.

**Comment by henryiii** [comment]
Originally, it was impossible to "end" an unlimited option for a positional since there was no way for a positional to start taking values. The idea was that this could be a workaround:

```bash
./test a b c --test2 d --test2 e --test2 f
```

However, the underlying problem was fixed in CLI11 1.5, you can now use `--` to end an unlimited string of values to an option. So this "greedy positional" behavior could be removed (I might even consider this for a 1.5.1 release).
