### ISSUE TITLE
Manually set value of an option

### ISSUE THREAD

**Issue by imranashraf** [CLIUtils/CLI11#115]
The command line options are parsed `CLI11_PARSE(options, argc, argv)`. Is it possible to manually set the value of a single option to some value and still get validated?

**Comment by henryiii** [comment]
No, but you can call the validator yourself if you'd like:

```cpp
std::string msg = CLI::ExistingFile(value);
if(msg)
    return app.exit("ExistingFile(value)", CLI::ValidationError(msg));
```

(Validators return a help message if they fail, and always take a string argument.)

**Comment by henryiii** [comment]
Let me know if you have another question!

**Comment by imranashraf** [comment]
@henryiii thanks for your response and sorry for my delayed response. Actually I am looking more from the point of view that during the execution of an application, user can set certain options to one of the per-defined values. Whenever user sets an option, I wanted CLI11 to parse and check if it is a valid option (i.e. specified option exist and the provided value is one of the possible values for that option). Based on App test, I manage to do this on the lines of:

```c++
    void set(std::string opt_name, std::string opt_value)
    {
        // -- is because user will specify option without these
        std::vector<std::string> opts = {opt_value, "--"+opt_name}; 
        app->parse(opts);
        app->reset();
    }
```
Is there a better way to achieve this?

**Comment by henryiii** [comment]
Right now, not too much can be done in non-string form, due to the fact that the reference is stored internally in the lambda function.

You could manually run the validation if you want, might be a bit cleaner and won't reset all other existing values:

```cpp
void set(std::string opt_name, std::string opt_value) {
    // -- is because user will specify option without these
    Option* opt = get_options([opt_name](const Option* opt){
        return opt.check_name("--" + opt_name);}).at(0);
    op->clear();
    op->add_result(opt_value);
    op->run_callback();
}
```

I've fixed a couple of bits that were missing, so you can now do (after the PR):

```cpp
void set(std::string opt_name, std::string opt_value) {
    // -- is because user will specify option without these
    Option* opt = app.get_option("--" + opt_name);
    op->set_results({opt_value});
    op->run_callback();
}
```

I've added `set_results(std::vector<std::string>)`, which will allow you to avoid clearing the option if it was passed beforehand and you want to ignore that. I've also added `get_optiion(std::string)` to make it easier to get an option pointer.

**Comment by henryiii** [comment]
PS: Feel free to write a test case matching your use case and I'll try to include it.
