### ISSUE TITLE
Interleaving options and flags

### ISSUE THREAD

**Issue by sasq64** [CLIUtils/CLI11#122]
I want to be able to interleave options with flags like so;

`myCommand -flag0 file1 file2 file3 -flag1 file4`

and when parsing know which flags apply to which files. Since positional arguments are stored as a vector it gets a bit tricky; I can do it using a `check()` call that actually stores the file names, and then use a dummy vector as the target;

```c++
	opts.add_option("files", dummyVector, "Filename")->check([&](const std::string &n) -> std::string {
		realVector.push_back(make_pair(currentFlags, n));
		return "";
	});
```

but it would be easier if there was a version of `add_option` that accepted a function that took a `std::string`, and called it for each occurrence of the option.

**Comment by henryiii** [comment]
You have access to the original option order with `parse_order`; that's a list of `Option*` pointers in the original calling order. You could build it out of that. Basically loop over it, every time you find one of your flags, all positional options after get tagged with that flag.

You can call `add_option` with a function; the problem is due to the way the parsing works, that is called with the collected option values (`std::vector<std::string>` as the argument). You've noticed a clever trick; the validators/transformers check is run immediately on each option as it is parsed, rather than with the collected values.

**Comment by sasq64** [comment]
I'd rather not go through the list after, as I would need to duplicate work of the parser.

How about an `each(FUNCTION f)` method on `Opt` that doesn't return anything and a version of `add_option` that needs no target variable ? Would at least make it a little nicer;

```c++
 opts.add_option("files", "Filename")->each([&](const std::string &n) {
		realVector.push_back(make_pair(currentFlags, n));
	});
```

**Comment by henryiii** [comment]
I can't easily add `opts.add_option("files", "Filename")` because `opts.add_option("files", str)` is allowed. I could require an R-value, of course, but splitting the description out to a string should in theory work without having to use a `std::move`. Each seems like a good addition and has been added in the linked PR.

**Comment by henryiii** [comment]
Should be implemented. Use `{}` for your option (empty function, FYI), and use `->each(...)`.

**Comment by henryiii** [comment]
```cpp
opts.add_option("files", {}, "Filename")->each([&](std::string n) {
    realVector.push_back(make_pair(currentFlags, n));
});
```
