### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by henryiii** [CLIUtils/CLI11#14]
This is a general issue for discussion on unicode/wchar support.

My thought is to start by making typedefs (`using` aliases now)  for the main types of strings being used and main functions on strings, then it would be easy to change in one place. I could even do a check for C++17 and use `string_view` if available.

Any help from people who use extended chars appreciated.

**Comment by bindreams** [comment]
Hi folks, I'd like to contribute, but in a bit of a different direction as far as unicode support goes. My idea is to make this library support UTF-8 on all platforms, instead of supporting wide strings on Windows machines (as popularized by http://utf8everywhere.org/). I've already implemented this support in my own project by pre-processing argc and argv before passing them to CLI11, and also implementing my own file validators which accept utf-8.

Similar to how [Boost.Nowide](https://www.boost.org/doc/libs/master/libs/nowide/doc/html/index.html) does it, I have two functions: `narrow` converts a wstring to a string with utf-8 text, and `widen` does the opposite (immediately before passing the wstring to std::filesystem::exists for example). Additionally, I believe Windows loses information when passing argv to `main` (as opposed to [`wmain`](https://learn.microsoft.com/en-us/cpp/c-language/using-wmain?view=msvc-170) which accepts wstrings). So we also need to query arguments from the Windows API using `GetCommandLineW`.

I did some testing on a fresh Windows 10 installation with english locale. I'm passing the string `"Hello Halló Привет 你好 👩‍🚀❤️"` as a command-line argument and the program is writing that string to a file. Here's the comparison table between current CLI11 vs. my patches. cohost is Windows default terminal window, wt is Windows Terminal which has better unicode support.

|                              | Are strings shown properly? (in terminal/in output file) | Proposed |
|------------------------------|:------------------------------------------------------:|:--------:|
| cmd                          |                           no/no                        |  no/yes  |
| powershell 5                 |                           no/no                        |  no/yes  |
| powershell 7 (on cohost.exe) |                           no/no                        |  no/yes  |
| powershell 7 (on wt.exe)     |                          yes/no                        |  yes/yes |

I'd like to make a proper patch if you're interested.

**Comment by phlptp** [comment]
@henryiii  can comment.  I think my main concern would be making sure we don't add complexity/processing time to support wide strings/unicode for the majority of cases when it is not needed.   So if we can add support via alternate parse operations and/or some alternate output/config operations that could be quite useful.

**Comment by bindreams** [comment]
Sounds reasonable. I think `App::parse` would need a toggle for this anyway, since we don't want it querying windows api all the time (not when testing with custom argv for example). File validators are questionable - a filesystem operation will probably take way more time than any string manipulation, although I have not checked.

**Comment by BeErikk** [comment]
Just a thought, parse may be and could be different and simpler.

Windows desktop programs, both console and windows programs have their command line arguments stored in the _CommandLine_ member of the _RTL_USER_PROCESS_PARAMETERS_ structure which is part of their respective _PEB_ structure. The _CommandLine_ is of type _UNICODE_STRING_. These are all internal system structures. Usually, a user calls the _GetCommandLineW_ function to receive command line arguments. This function gives direct access to the buffer in _CommandLine_ and is of type _PWSTR_. This is true for both _ANSI_ and _UNICODE_ programs, both console and windows programs. The exception is the now-defunct _POSIX_ programs which have an altered UNIX-type _ASCII_ command line by the _POSIX_ subsystem. 

Thus, the most efficient way to process command-line arguments in Windows is to parse the buffer received from _GetCommandLineW_ and parse it as UTF-16 (16-bit _wchar_t_). Strings can then correctly be converted to UTF-8 if so is desired.

The  _CommandLine_ buffer looks like this:
"_programpath" arg1 arg2 ...._
So a typical parser skips everything until the second quote + 1 space. The arguments are then available as a space-delimited string to be split.

Note: The _GetCommandLineA_ function gives a _char_ allocated buffer where the _CommandLine_ buffer is copied and converted to the current system ANSI multi-byte codepage. It's also what you get if you parse the _argv_ in ANSI/MBCS console programs where the startup code already has preprocessed the command-line into _argc_ and _argv_.

**Comment by bindreams** [comment]
> Thus, the most efficient way to process command-line arguments in Windows is to parse the buffer received from GetCommandLineW and parse it as UTF-16 (16-bit wchar_t).

Unless I misunderstand, this is basically what I implemented for windows-oriented code in #804.
https://github.com/andreasxp/CLI11/blob/9bda850c165c3e38e4479272b445306453cf3f3e/include/CLI/impl/Argv_inl.hpp#L82

The main difference from your suggestion is that parsing is done by CommandLineToArgvW instead of manually. This avoids us dealing with nasty corner-cases of parsing, such as arguments with spaces in quotes, escaped quotes, etc.

**Comment by BeErikk** [comment]
> The main difference from your suggestion is that parsing is done by CommandLineToArgvW instead of manually. This avoids us dealing with nasty corner-cases of parsing, such as arguments with spaces in quotes, escaped quotes, etc.

Nice and seems to integrate well into CLI11 code. A solution which I believe also solves the issue when using _wmain_ in console. I support your patch, I just wanted to point out the background and show an alternate possible route by splitting the command-line string directly and skip the argv parsing altogether. Since it is a space-delimited string the arguments could be stored in a std::vector with a few lines. Regarding complexity, the _CommandLineToArgvW_ function is fine but rather simple. Similar code can be found at _Windows Kits\10\Source\<version>\ucrt\startup_, especially the quoting rules (see _parse_command_line_). That said I have no solution to integrate this idea into CLI11.

**Comment by phlptp** [comment]
Probably feels kind of good to close out the oldest issue?  Nice work!!  :+1:
