### ISSUE TITLE
Make CMake install options for standalone only

### ISSUE THREAD

**Issue by robiwano** [CLIUtils/CLI11#156]
By having a CMake variable:
```
unset(CLI11_STANDALONE)
if (${CMAKE_SOURCE_DIR} STREQUAL ${CMAKE_CURRENT_SOURCE_DIR})
    set(CLI11_STANDALONE TRUE)
endif()
```
it can be used to disable install(...) directives, so CLI11 can be used as a submodule in a larger project.

**Comment by henryiii** [comment]
Please verify this is now fixed in master through #159. I've used CLI11_INSTALL - it deactivates most of the installs if this is a subproject always, hopefully I left in the right bits to allow the CLI11 target to still work as a dependency of a parent project through the config script.

That is, `find_package(NewProject CONFIG)` should produce working targets even if `NewProject`'s targets depend on `CLI11::CLI11` and `CLI11` is not found separately.
