### ISSUE TITLE
add support for click-style boolean flags

### ISSUE THREAD

**Issue by pwm1234** [CLIUtils/CLI11#217]

**Comment by pwm1234** [comment]
First let me say thanks for your work on CLI11 and making it available. CLI11 is a big help to me.

I am also a user of click for my python programs, and I like how CLI11 supports many of the features of click. One click feature that I would like to see in CLI11 is how to set boolean flags with the "--option/--no-option" syntax (see [Boolean Flags](https://click.palletsprojects.com/en/7.x/options/#boolean-flags)). Is this capability somewhere on the roadmap? If not, is it something you would consider adding? Any suggestions on how to go about implementing this in a pull-request that you would consider for merging?

**Comment by henryiii** [comment]
I guess this has only been talked about in emails and maybe gitter. Yes, it's an oft-requested feature, and I'd be glad to get it in CLI11. I'd like to have flexibility in the "no-" prefix, and stay with the current Option-only design (flags are just options internally). First thing is to cover the API. How would you expect this to be activated when a user adds a flag? Is it settable on the default option? Does it make any sense to do any different for regular options too (I think not)? @phlptp might have ideas and/or suggestions.

**Comment by henryiii** [comment]
PS: I don't think I've looked at the click syntax yet, that might be interesting.

**Comment by pwm1234** [comment]
Click uses an option with a boolean value for what CLI11 calls a flag. The (primary) click api is ``@click.option('--shout/--no-shout', default=False)``. Click also has an ``is_flag`` argument if you want to leave out the ``--no-`` switch. I am not quite sure a good way to map this to the CLI11 flag api. 

The logic seems to be:

1. not require (or not accept) values for bool options (aka flags). 

2. to recognize both the ``--option`` and the negated ``--no-option`` for the same variable, where ``--option`` sets the variable to true and ``--no-option`` sets the variable to false. 

For CLI11 this seems to be neither an option nor a flag. (It is an option without a specified value; it is a flag that needs to set a bool variable.) Perhaps the clearest CLI11 approach would be to add a new method ``CLI::App::add_flag_negatable(std::string flag_name, bool& flag, std::string description="")``.

**Comment by phlptp** [comment]
I have poked it a little as well, and it is something I would probably try to implement in a couple months unless I get inspired sooner or it becomes more urgent on our projects.  I think I need to understand better how the internals of the flag options work first.  But my initial thought was to add a method to options `add_negation_prefix(string)`  or something to that effect.  which would trigger on long form options such that if it were specified like "--flag"  And the negation prefix were set to "no"  the option would also trigger on --no-flag but have false value.    Not entirely clear how that would work internally yet, and with counts and the callback options there are lots of little issues like that would need to be sorted out.    

The add negation prefix would probably throw an error if an argument was required just to prevent some oddities.  

I think you would want to be able to control the prefix since some apps would likely want --no-** others might want --disable-**   and who knows what you might want if the app is not English based.

**Comment by henryiii** [comment]
How about this (just thinking here, nothing coded or set in stone):

The add flag functions allow the special syntax from Click:

```cpp
app.add_flag("--shout/--no-shout,-s/-n");
```

This fills in two new lists: `neg_short_name_` and `neg_long_name_`. If a user tries this syntax on a normal option, it will fail. I don't think the short version would be popular, it could be only allowed on long names and that would save one list. Both normal and negation lists would need to be searched, checked for duplicates, etc., and would probably be the biggest change/challenge.

In parsing, if a flag was found in the negative list, it would get "negated" (whatever that means).

Then, the question is what does negation mean:

```bash
./app --shout                       # count = 1
./app --shout --no-shout            # count = 0
./app --no-shout --shout            # count = 1?
./app --no-shout                    # count = 0
./app --no-shout --no-shout --shout # count = 1?
./app --shout --shout --no-shout    # count = ?
```

There's also an enum that modifies what multiple options mean, this could allow choices here too. Like `CLI::take_last`.

Internally, this would mean when the flag is aggregated, it would get a different number of empty strings passed to it. I *think* this would work well with defaults, since a defaulted option just never runs. Options with 0 arguments would be 0 or false (bool).

**Comment by pwm1234** [comment]
From my perspective (and usage of click), I do not need or want the complication of what to do for the presence of multiple negatable options. I would want only ``take_last``. 

BUT ... I do like the click feature where the default can be true. For example

    ./app                                   # count = 1
    ./app --shout                           # count = 1
    ./app --no-shout                        # count = 0

Could the default count of 0 or 1 (perhaps better true or false) be an extra argument to the ``add_flag`` method?

**Comment by phlptp** [comment]
```
app.add_flag("--shout/--no-shout,-s/-n");
```

I like the concept of this syntax!  It would also allow things like ("--verbose/--quiet"  instead of just a prefix.    

I have been a little curious what the use case was for the count as being something other than 0 or 1.    The only think I could come up with was something like verbosity  where -v meant something different than -vv or -vvv,

honestly I don't imagine there are too many people that would use the negation syntax with anything other than the single bool variable or callback.    If practical limiting it to those calls would probably be sufficient for nearly all use cases, in which case the count discussion becomes moot.  

Otherwise you could also consider putting a `+` or `-` instead of the empty strings the CLI::result_t for the flag arguments.

**Comment by phlptp** [comment]
@pwm1234   just wondering on your opinion on #219 before it gets closed out.  
The gist of it is that for the add_flags functions they allow a syntax like `--flag,!--no-flag` or `--flag,--no-flag{false}`  to support default false triggered flags.    This is different than the click syntax but has a similar function.

**Comment by pwm1234** [comment]
Wow this is great! I am not sure how you, @phlptp, made such a contribution while on paternity leave, but this functionality seems to be exactly what I was asking for. Thank you.

**Comment by phlptp** [comment]
Partly cause it is kind of fun to work on a different project without work pressure and partly because the baby actually sleeps at night pretty well, so I actually feel almost normal most days, so I get a couple hours during the mornings to actually tinker.
