### ISSUE TITLE
std::optional<std::vector<double>> doesn't compile

### ISSUE THREAD

**Issue by jiggersplat** [CLIUtils/CLI11#257]
The following does not compile:

`app.add_option("-v,--vec", std::optional<std::vector<double>>, "some vector")->expected(3);
`

I can just check length as a work-around, but thought I would put this out there. Not sure this is a common or easy to support use-case.

**Comment by phlptp** [comment]
I think right now optional only works with types that support >> operator.  I think it would take some template magic on the add_option templates to separate the actual storage type from the conversion types and even then I am not sure the it would work to assign the result to the optional containing a vector since you need an indirect to use the methods on an optional.  

In which case you best bet if you really want an optional would be to use
```cpp
std::optional<std::vector<double>> opt;
add_option_function<std::vector<double>>("-v,--vec", [&opt](auto &v){opt=v;}, "some vector")->expected(3);
```
This will only work on master right now, not 1.7 release

 @henryiii might have a better idea

**Comment by henryiii** [comment]
Optional's of normal values are supported (>> operator), but not sure why you'd want an optional vector. Can't the vector just be empty if no arguments are passed?

**Comment by phlptp** [comment]
this actually works now if you use the two parameter template for add_option, and you can specify expected_size(0) on the option if you actually wanted it to be optional.
