### ISSUE TITLE
Setting default values do not take effect

### ISSUE THREAD

**Issue by xieepp** [CLIUtils/CLI11#26]
```cpp
int test = 0;  
app->add_option("--test", test, "Test the default value.")->set_default_val(std::to_string(200));  
app->parse(argc, argv);
std::cout << test << endl; // output:0, want: 200
```

**Comment by henryiii** [comment]
That's because `set_default_val` sets the default value string, the initial value is set by
```
int test = 200;
```

Would it be best to change `set_default_val` to `set_default_str` to make it clearer, or is there a use case for actually having it evaluate the default value string, either immediately (easier) or when it parses (harder to implement cleanly)?

**Comment by xieepp** [comment]
I think evaluate immediately would be enough~

**Comment by henryiii** [comment]
Let me know if that fixed it for you!

**Comment by xieepp** [comment]
Works fine, thanks very much!
