### ISSUE TITLE
Is there a way to alias a subcommand?

### ISSUE THREAD

**Issue by comfortablynick** [CLIUtils/CLI11#288]
I would like to have subcommands with multiple names (long and short), such as `a`|`add` or `i`|`install`. Is there a way to do this without duplicating all of the command definitions?

Thanks!

**Comment by phlptp** [comment]
Not that I know of directly.  The closest right now would be to create a shared_ptr to an app(do NOT give it a name) with all the options for a particular subcommand.  

Then in the main app create a subcommand for each of the names you want to be the same, and call add_subcommand(shared_app)  with the shared_ptr to the option_group that contains all the actual options.  Fallthrough will always go up to the last subcommand you added it to, but otherwise should work as you expect unless you are doing interesting things with the callbacks on the apps and option groups.

**Comment by phlptp** [comment]
The current master branch has an `alias` function that will do this now.
