### ISSUE TITLE
[Question] Dynamic Flags

### ISSUE THREAD

**Issue by sergeyklay** [CLIUtils/CLI11#351]
Hi!

This is not an issue, but more a question. And I'm sorry if I chose the wrong place to ask questions.

Is it possible to create a kind of _dynamic flags_, if yes, could you please provide a small example of parsing and using such flags.

Expected behavior:
```sh
$ ./app --help
app 1.0.0

Usage:
  command [options] [arguments]

Options:
  # some options

Available commands:
  cmd1            Description
  cmd2            Description
  cmd3            Description
  # another commands

$ ./app cmd1 --help

# ...

Common flags are:
  -f([a-z0-9\-]+)    Enables compiler optimizations
  -fno-([a-z0-9\-]+) Disables compiler optimizations
  -w([a-z0-9\-]+)    Turns a warning on
  -W([a-z0-9\-]+)    Turns a warning off
```

Thus, for example, user will able to use app as follows:
```
$ ./app cmd1 -Wimplicit-int -Winvalid-pp-token
```

Some notes:
- Desired flags has single dash form (`-`) and each flag definition provided in regexp form.
- I'll need to understand which flags was passed
- I don't have a constant list of flags (amount of flags may grow dynamically). For example user can extend application using a "plugin" that provides its own flags
- Somewhere in app I'll do a check (pseudocode):
```
if ( flag_is_passed(name) ) {
   // do some stuff
}
```

Thank you

**Comment by phlptp** [comment]
I will try to tackle most of this question,  maybe more later
the single '-' long options are [explicitly not supported by this library](https://github.com/CLIUtils/CLI11#features-not-supported-by-this-library)

That being said f,w, and W are all single characters in which case '-' would work fine and you would get the flag string as the argument.  So you can probably work around it.  

in general for flags you can define negative flags 
```cpp
app.add_flag("--flag,!--no-flag",result,"help for flag");
```
or 

```cpp
app.add_flag("--flag,--no-flag{false}",result,"help for flag");
```

though that wouldn't work if you need the flag as an argument for a single '-' option.

For a subcommand you can also just force all arguments to be positional then the '-W{FLAG} syntax will process just fine but you will need to parse it yourself.

For dynamic flags it is possible to add and remove flags in one of the callbacks of a subcommand or option group if you needed to do it in the middle of a parse.  

Otherwise I have used  a cascade of parsers where the second level of parsing gets created in the callback of the first subcommand.  Or use
```
app->remaining_for_passthrough ();
```
to get the unprocessed args and feed them to the next level.  

Flags/options can also be build in pieces by just creating an app as a shared pointer and adding it to a higher level one,  I have done this before to build command line parsers where one component cannot know all the options but knows which pieces to call to generate a CLIapp.  These groups can be turned on and off dynamically if need be.

**Comment by sergeyklay** [comment]
@phlptp Thank you for a such detailed explanation. I think I get the general idea.
