### ISSUE TITLE
Issues in saving/loading config with flag defaults

### ISSUE THREAD

**Issue by jbriales** [CLIUtils/CLI11#364]
When saving config with default values, i.e. `app.config_to_str(true, true)`, flags get saved as false.
However when reading that same config, the flags get evaluated to true.

I created a toy test in https://github.com/CLIUtils/CLI11/pull/363 to quickly showcase this.

@phlptp  this might be (maybe) addressed in your WIP (https://github.com/CLIUtils/CLI11/pull/362)?

**Comment by phlptp** [comment]
I was wanted to look through some of that, but hadn't got to that aspect yet.  
If you would like you can make pr of that test into https://github.com/phlptp/CLI11/tree/config_file_refactor

and I will see if I can figure out what is going on over the next few days.

**Comment by jbriales** [comment]
I see you already merged my test PR into your branch. Thanks! ;)

**Comment by phlptp** [comment]
I merged it in.  Interestingly I am pretty sure that bug has been there since config writing was added.  It just was made a little easier to get to when flags could be more than just "true" or not there.  I fixed the bug for the specific test case but in the process it broke a number of other tests so I am still evaluating how to handle them.
