### ISSUE TITLE
Question: toggling bits with flags

### ISSUE THREAD

**Issue by emKaroly** [CLIUtils/CLI11#372]
Is there any easy way how can i toggle bits in a integer variable with flags?

**Comment by phlptp** [comment]
the simplest way would be with a callback functions to a flag
say if you wanted a flag to set the 7th bit of an integer

```
uint32_t flags{0};
app.add_flag_callback("--flag",[&flags](){flags|=(1<<7);},"flag descriptions");
```

depending on exactly what you wanted to do
`add_flag_function` has a few more options since it executes the callback with a int64_t parameter so you can design the flags to have an integer associated with them  (default is -1 for false 1 for true)  so anything <=0 should be considered false.

**Comment by emKaroly** [comment]
Ok. Thank you thats exactly what i am doing now, i just thought i overlooked something in documentation.
