### ISSUE TITLE
Unclear exact semantics of add_flag(std::string, bool&), possible undefined results

### ISSUE THREAD

**Issue by himikof** [CLIUtils/CLI11#411]
I was trying to understand the best way to use a simple boolean flag in this library, and found during my experiments that the following test surprisingly fails (`value` is not set to `false`):

```c++
TEST_F(TApp, EmptyBoolFlag) {
    bool value = true; // Should be ignored?
    app.add_flag("-b,--bool", value);
    args = {};
    run();
    EXPECT_EQ(0u, app.count("--bool"));
    EXPECT_FALSE(value);
}
```

There are a lot of examples of `add_flag` usage like (book/code/flags.cpp):
```c++
bool flag_bool;
app.add_flag("--bool,-b", flag_bool, "This is a bool flag");
```
Do they currently leave the value undefined if the flag is not passed? Or the usage is wrong?
I think that using a similar `add_option` overload without any default is incorrect, but `add_flag` seems like a different case.

**Comment by phlptp** [comment]
The add_options will not modify the value if no input is passed.  add_flag does the same thing.  Flags can default to true/false or other so assuming something about it doesn't seem like the correct thing to do and could lead to issues.   

So basically if no option/flag is passed in the command line, the value is not modified.    It is possible to specify.

`->defaultval(false);  to the option that would set the value to false.  

You know as I think about this a little more the `defaultval` behavior should be a little clearer, and probably executed on reset as well so if the app is called multiple times the value is modified on reset to the default value.    A `forced()` option might also be appropriate so an option is always guaranteed to update the value or call a callback, regardless of whether an option is passed or not.  

Regardless at the moment the above behavior is as expected and designed.    Whether that should be case or allowed to be modified might be worth some discussion.

**Comment by himikof** [comment]
So if this flag behavior is expected, all `add_flag(std::string, bool&, ...)` calls without an explicit `= false` initialization (and without `default_val`) are broken and should be fixed? It seems that there are currently such examples in both docs and tests. I don't think this behavior is clear from the documentation now.

It would be unfortunate if the most simple way to use `add_flag` API is also wrong, users need to remember either to initialize to variable manually, or to always call `add_flag(...)->default_val(false);`

Also, the API invariant of "do not modify the value passed by reference if `option->count() == 0`" already does not hold for `add_flag(std::string, int&)`: the counter is eagerly set to zero there, and I assume that is intended. So the code
```
int flag_count;
app.add_flag("--count", flag_count);
```
works, but the same code with `bool` does not.

**Comment by phlptp** [comment]
I suppose the calls without an initialization could result in undefined behavior.    Those cases should be fixed in the docs and the behavior should  probably be clarified.  

As far as the general behavior I would argue that without instructions to do otherwise (via default_val)  there is no way CLI11 could operate on the storage location, since there is no way to determine a default value.    Anything else would be wrong and very problematic.  There are means of checking whether the flag is passed so even giving it an undefined value is not necessarily undefined behavior and would depend on how it gets used by the surrounding code.  

The example of the counting flag is somewhat due to backwards compatibility and is planned to be changed in 2.0 as it is inconsistent with the behavior of the rest of the library. 

Still going back on the idea of a `force` option for the options/flags that would guarantee a callback is called or a value is set.

**Comment by henryiii** [comment]
Should be done correctly now in tests and docs, and backported to v1.
