### ISSUE TITLE
BUILD_TESTING=ON requires downloaded googletest when it is already installed

### ISSUE THREAD

**Issue by yurivict** [CLIUtils/CLI11#412]
Please use the installed googletest.

**Comment by henryiii** [comment]
While this can be supported, Google's own recommendation it that Googletest never be installed, and they even go to the trouble to remove `make install` from the build system.


We may change to a different download method for google test, and this would be a good change to make then.

**Comment by yurivict** [comment]
Downloaded packages only work on Linux. On BSDs build would likely fail due to the need for patches, etc, and packaged versions of all dependencies should be preferred.

**Comment by henryiii** [comment]
We are requiring an exact (current master) version of GTest since they don't release often (google internally lives at head, and have said google test will receive rare updates since it is supposed to be used at head), and we need the C++20 fixes. GoogleTest also goes to great lengths *not* to be installable, since it is not supposed to be installed as a package.

It's also not a dependency. If it doesn't work due to issues in googletest that are patched in FreeBSD packages, just don't build the tests. And ask the maintainers to please try to upstream fixes. Generally only binaries should be patched; patching a header can break the API.

Does it not work on FreeBSD?

**Comment by phlptp** [comment]
@henryiii  I think this can be closed since you use Catch2 now

**Comment by henryiii** [comment]
We also support external Catch 2 now too (didn't at first).
