### ISSUE TITLE
Support returning string values as std::span objects instead of std::string ones

### ISSUE THREAD

**Issue by KOLANICH** [CLIUtils/CLI11#427]
It should be more efficient since these stuff is already allocated, so no need in additional heap allocations and copies.

**Comment by phlptp** [comment]
std::span in a C++ 20 construct.  Obviously we couldn't include any reference to it directly to maintain compatibility.  

I think getting values by string_view already works,  I am not sure it would be appropriate to get by span, since you wouldn't want to be able to modify the internal values, which is what a span would allow, so it would need to be copied anyway otherwise a const span is pretty similar to string_view.

for values other than the string the converted values are generated dynamically so a span would have lifetime issues.

**Comment by KOLANICH** [comment]
Thanks, I haven't known about `string_view`.
