### ISSUE TITLE
Visual Studio 2019 IntelliSense add_option() "no viable function" error

### ISSUE THREAD

**Issue by BullyWiiPlaza** [CLIUtils/CLI11#428]
When using the `add_option()` function in `Visual Studio`, `IntelliSense` complains about `no viable function`:

![image](https://user-images.githubusercontent.com/7620135/74271549-5d182b00-4d0d-11ea-8809-1073bc735aca.png)

Is there a way to fix `IntelliSense` in that regard?
![image](https://user-images.githubusercontent.com/7620135/74271639-88027f00-4d0d-11ea-8e1c-87cfadcaf0bb.png)
The function takes 3 arguments and 2 more are optional. Looks fine to me but how do we "convince" `IntelliSense` as well?

The code compiles successfully but the red squiggles in the editor are annoying and distracting.

**Comment by phlptp** [comment]
I have used VS 2019 and have not noticed the same issue, but intellisense is sometime funny that way.  
Are you using the single header or library?   And from the screen shot it looks like one call is not showing up as flagged by intellisense.  

I know sometimes rescanning or clearing and rebuilding the intellisense database fixes things like that.  

Did you recently update CLI11?  If so you might have to rescan the intellisense since some of the templates for add_option changed.  It may still have the old definition somewhere in its database.

**Comment by BullyWiiPlaza** [comment]
I deleted the `.vs` file and reopened my `CMake` based project in `Visual Studio`. `IntelliSense` however flagged the same methods once again. I'm using the includes listed [here](https://github.com/CLIUtils/CLI11/tree/master/include/CLI).
I installed them via the package manager `vcpkg`. This is the default behavior by the `vcpkg` for installing `CLI11`.

**Comment by songyibo** [comment]
Same issue with VS 2015.
I'm using CLI11 1.9.0 single header. Though it compiles fine.

**Comment by cronchie** [comment]
I think this is the issue: `https://developercommunity.visualstudio.com/t/msconnect-3141430nested-stdenable-if-breaks-intell/246988`

Looks like it has a problem with the overload accepting `AssignTo`. Intellisense has an issue with the nested `enable_if`, but it still compiles successfully.

Edit: maybe this is actually a ReSharper bug? I disabled ReSharper and the warning went away.

![image](https://user-images.githubusercontent.com/6097369/121055435-3f38ca00-c78b-11eb-9865-e44806bfd40a.png)

^ Starting sample with and without ReSharper enabled
