### ISSUE TITLE
Invalid handling of repeated arguments and positional arguments

### ISSUE THREAD

**Issue by ulfllorenz** [CLIUtils/CLI11#493]
For evaluation, I created a small test program with CLI11 and immediately noticed some failures. For example, the command line

TestProgram --int=1 -i 2 --int=3 blah blubb

fails with (for the normal user) an incomprehensible error message. 
Once I figure out how to attach files, you also get the example program with some comments describing failing command lines.

**Comment by ulfllorenz** [comment]
[TestProgram.cpp.githubdoesnothandlecpp.txt](https://github.com/CLIUtils/CLI11/files/4994436/TestProgram.cpp.githubdoesnothandlecpp.txt)

**Comment by phlptp** [comment]
The failure is the result of vector arguments allowing multiple argument per option.  In that circumstance the first `blah` is included with the --int since it is a vector.  

It will automatically fill in the positional if there is only one argument left so the last one doesn't apply.  

If you only want 1 argument per call, then the modifier `->allow_extra_args(false);`  should be added to the integer option, this will only allow 1 per call, and the final two argument will get interpreted as positional.

**Comment by ulfllorenz** [comment]
This comes too late for the specific problem, but thanks for the illumination.
