### ISSUE TITLE
Option variables are not populated when the -h flag is provided

### ISSUE THREAD

**Issue by SkyToGround** [CLIUtils/CLI11#57]
Consider the following code:

```c++
#include "CLI11.hpp"
int main(int argc, char **argv) {
  CLI::App test;
  std::string some_option;
  test.add_option("-a", some_option, "Some description");
  try {
    test.parse(argc, argv);
  } catch (const CLI::Error &e) {
    std::cout << "Option string:" << some_option << std::endl;
    return test.exit(e);
  }
  std::cout << "Option string:" << some_option << std::endl;
  return 0;
}
```

When passing ``-h`` to the application, the ``some_option`` variable is empty regardless of if ``-a`` has been used. This makes it hard to deal with some use cases where you want to handle partially incorrect command line arguments or context based help.

**Comment by henryiii** [comment]
Help flags intentionally quit as soon as possible, to be as fast as possible, avoid configuration file parsing or environment parsing, and `required`/`excludes`/`requires`, option callbacks, etc. You can easily make a help flag that runs afterwards, though; that's really just a normal flag:

```cpp
#include "CLI11.hpp"
int main(int argc, char **argv) {
  CLI::App test;

  // Remove help flag because it shortcuts all processing
  test.set_help_flag();

  // Add custom flag that activates help
  auto help = test.add_flag("-h,--help", "Request help");

  std::string some_option;
  test.add_option("-a", some_option, "Some description");
  
  try {
    test.parse(argc, argv);
    if(*help)
        throw CLI::CallForHelp();
  } catch (const CLI::Error &e) {
    std::cout << "Option string:" << some_option << std::endl;
    return test.exit(e);
  }

  std::cout << "Option string:" << some_option << std::endl;
  return 0;
}
```

In my case, I compiled with `c++ -std=c++14 modhelp.cpp -Iinclude` and it behaved as expected. You can use a different style of flag if you want, but you can't use a function callback flag that throws, since you can't ensure the help flag will be last. (Technically, since options always process in definition order, if you make the help flag last, you probably could do that instead if you were careful.)

**Comment by SkyToGround** [comment]
That solution works well with my intended use case. Thanks!

**Comment by henryiii** [comment]
Okay, thanks! I'll add it as an example.
