### ISSUE TITLE
1.10.0 release

### ISSUE THREAD

**Issue by AnticliMaxtic** [CLIUtils/CLI11#596]
Could we get a 1.10.0 release with at least the changes from 3eb5e1eedd3504465ff72773e300d0440a215493 pulled in so that we can get Conan/vcpkg builds with that change in it?

**Comment by henryiii** [comment]
If someone wants to help backport it - it's really tricky (I've tried) due to the CI changes needed to get this passing (I don't want to make a release if I can't get CI to pass), and there were several things that were needed. I'm bumping 2.0 up on my priority list (and my daughter is 4 months old now, so starting to get extra time again).

**Comment by henryiii** [comment]
2.0 is out, so going to close this. Ping me if there's anything I need to do with the various distributions (like Conan/vcpkg).
