### ISSUE TITLE
Can I just read the parsed results from CLI::app rather than manually defining every variable for that?

### ISSUE THREAD

**Issue by Yanhao** [CLIUtils/CLI11#86]
Doesn't find the answer from the document.

**Comment by Yanhao** [comment]
related question: can I add options by only specifing the type of the expected value?

**Comment by henryiii** [comment]
You do need to make a variable for each option; it was designed to avoid a map lookup for each variable, so that's why it's explicit in the current version of the parser. You can, however, check the status or the text for a variable without accessing the defined variable. And flags do not need to have a manual variable specified.

I've got general plans to work on the way the variable storage works that might change this in the future, but nothing that I'm sure of yet. It adds a complication: you have to have template classes for options which may add syntax burden on the user (at least before C++17, and I think I might have a solution). I probably won't have time to work on a change this large for a few months.

**Comment by Yanhao** [comment]
got it, thanks for replying
